# Generated by Django 3.2.6 on 2021-08-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성'), ('etc', '기타')], max_length=6, verbose_name='성별'),
        ),
    ]
