# Generated by Django 3.2.6 on 2021-08-19 00:37

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(null=True, upload_to=comments.models.image_directory)),
                ('audio', models.FileField(blank=True, null=True, upload_to=comments.models.audio_directory)),
                ('gif', models.FileField(blank=True, null=True, upload_to=comments.models.gif_directory)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
