# Generated by Django 3.2.6 on 2021-08-19 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0003_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0002_feed_user'),
        ('likes', '0002_replylike_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='replylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사람'),
        ),
        migrations.AddField(
            model_name='feedlike',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feedlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사람'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='comments.comment', verbose_name='댓글'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사람'),
        ),
    ]
