# Generated by Django 3.2.6 on 2021-08-23 01:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='내용')),
                ('random_nickname', models.CharField(default=core.models.default_random_name, max_length=20)),
                ('audio', models.FileField(null=True, upload_to=core.models.audio_directory)),
                ('image', models.ImageField(null=True, upload_to=core.models.image_directory)),
                ('num_comments', models.IntegerField()),
                ('num_likes', models.IntegerField()),
            ],
            options={
                'db_table': 'feeds',
                'ordering': ['-created_at'],
            },
        ),
    ]
