# Generated by Django 3.2.6 on 2021-08-19 00:37

from django.db import migrations, models
import feeds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(verbose_name='내용')),
                ('audio', models.FileField(upload_to=feeds.models.audio_directory)),
                ('image', models.ImageField(upload_to=feeds.models.image_directory)),
            ],
            options={
                'db_table': 'feeds',
            },
        ),
    ]
