# Generated by Django 3.2.6 on 2021-08-20 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feeds.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0002_feed_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feed',
            name='random_nickname',
            field=models.CharField(default='진화된 무선 전자시장', max_length=20),
        ),
        migrations.AlterField(
            model_name='feed',
            name='audio',
            field=models.FileField(null=True, upload_to=feeds.models.audio_directory),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(null=True, upload_to=feeds.models.image_directory),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
