# Generated by Django 3.2.6 on 2021-08-19 00:37

from django.db import migrations, models
import django.db.models.deletion
import replies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0002_comment_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to=replies.models.image_directory)),
                ('audio', models.FileField(blank=True, null=True, upload_to=replies.models.audio_directory)),
                ('gif', models.FileField(blank=True, null=True, upload_to=replies.models.gif_directory)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'db_table': 'replies',
            },
        ),
    ]
