# Generated by Django 3.2.6 on 2021-08-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0002_reply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
